### ISSUE TITLE
Where does the provider come from?

### ISSUE THREAD

**Issue by o-az** [lxsmnsyc/solid-marked#1]
In the readme it shows the following:

```ts
const { map, code } = await compile(
  'mdx-provider',  // Where to import the builtin components
  'my-file.md',    // Name of the file
  '# Hello World', // Markdown code
);
```

Where does the mdx provider come from? Looking at the [mdx-js](https://mdxjs.com/docs/getting-started/) docs I see Providers but they're coming from specific packages like the next or react package. Do we have one for Solid where I can import the provider? 

Is there anyway you could provide a full example of how to render mdx file that includes components/syntax? I will happily help with anything I can.

**Comment by lxsmnsyc** [comment]
Sorry if it wasn't documented properly. `'my-provider'` is meant to be a module that would export the function `useMDX` which returns [an object that would be the source of components](https://github.com/LXSMNSYC/solid-marked/blob/main/packages/solid-marked/src/interfaces.ts#L84) to be used by the compiled Markdown.

For example, if we have a module `markdown-ui` and markdown input of `Hello World` the MDX file would output something like

```js
import { useMDX } from 'markdown-ui';

export default function Component(props) {
  const ctx = useMDX();
  
  return (
    <Dynamic component={ctx.builtins.Root}>
      <Dynamic component={ctx.builtins.Paragraph}>Hello World</Dynamic>
    </Dynamic>
  );
}
```

**Comment by o-az** [comment]
Is there anyway you can share an example of rendering a an mdx file as a SolidJS component with syntax highlighting? I've been trying for a while but can't get the syntax part to work. I will create an environment for you on stackblitz. Much appreciated.

**Comment by o-az** [comment]
Here's a link to a stackblitz project. Any insight on how to get actual formatted mdx with syntax highlighting rendered instead of a bare string?

https://stackblitz.com/edit/vitejs-vite-eaprur?file=src/main.tsx

**Comment by lxsmnsyc** [comment]
I'm sorry but for this to work properly it would require bundler support, in which case we need to write a plugin for Vite so that it can handle the markdown files.
