### ISSUE TITLE
Github pages demo

### ISSUE THREAD

**Issue by martin-juul** [lxsmnsyc/solid-marked#2]
A demo page with the current capabilities would be awesome for people who (like myself) are curious about what it can do.

**Comment by lxsmnsyc** [comment]
Yes. I have been working on approaching bundler plugins so we would see it anytime soon.

**Comment by lxsmnsyc** [comment]
I've released the Vite plugin and added a little Vite demo: https://codesandbox.io/s/github/LXSMNSYC/solid-marked/tree/main/examples/vite-demo
