### ISSUE TITLE
HTML/JSX expressions cause `__ctx is not defined`

### ISSUE THREAD

**Issue by zhengkyl** [lxsmnsyc/solid-marked#6]
I have a markdown file like this
```
<Example/>
```
and I get this error `__ctx is not defined` when `noDynamicComponents` is false.

It seems that `__ctx` was changed to `_ctx$` at some point but it got overlooked in this case.

I got it working by doing a replace all, but this leads to a second issue.

Now I am not sure how to get JSX and HTML working at the same time. If `noDynamicComponents` is true, HTML works and custom components are undefined, and if `noDynamicComponents` is false, JSX works and HTML isn't rendered. 

I dug around a bit, but couldn't figure out why, but that isn't a dealbreaker for me and I'm not sure if I'm missing something.

**Comment by lxsmnsyc** [comment]
should be fixed in 0.6.2
